controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # This publishes the 3D position of your robot joints
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # This handles the velocity of your 6 wheels
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

velocity_controller:
  ros__parameters:
    joints:
      - Revolute 10
      - Revolute 11
      - Revolute 12
      - Revolute 13
      - Revolute 14
      - Revolute 15
    interface_name: velocity